interface User {
  id: string;
  name: string;
  email: string;
  salary: number;
  gender: string;
  dob: Date;
  position: string;
  joiningDate: Date;
  isEditing: boolean;
}

export const DEMO_USERS: User[] = [
  {
    id: '1',
    name: 'Alice',
    email: 'alice@example.com',
    salary: 500,
    gender: 'female',
    dob: new Date('1995-06-15'),
    position: 'Developer',
    joiningDate: new Date('2022-01-10'),
    isEditing: false,
  },
  {
    id: '2',
    name: 'Bob',
    email: 'bob@example.com',
    salary: 600,
    gender: 'male',
    dob: new Date('1990-02-20'),
    position: 'Designer',
    joiningDate: new Date('2021-05-01'),
    isEditing: false,
  },
  {
    id: '3',
    name: 'Charlie',
    email: 'charlie@example.com',
    salary: 750,
    gender: 'male',
    dob: new Date('1988-10-05'),
    position: 'Project Manager',
    joiningDate: new Date('2019-03-12'),
    isEditing: false,
  },
  {
    id: '4',
    name: 'Diana',
    email: 'diana@example.com',
    salary: 620,
    gender: 'female',
    dob: new Date('1992-09-25'),
    position: 'QA Engineer',
    joiningDate: new Date('2020-11-19'),
    isEditing: false,
  },
  {
    id: '5',
    name: 'Ethan',
    email: 'ethan@example.com',
    salary: 540,
    gender: 'male',
    dob: new Date('1996-04-10'),
    position: 'Frontend Developer',
    joiningDate: new Date('2021-07-30'),
    isEditing: false,
  },
  {
    id: '6',
    name: 'Fiona',
    email: 'fiona@example.com',
    salary: 690,
    gender: 'female',
    dob: new Date('1993-01-22'),
    position: 'UX Designer',
    joiningDate: new Date('2020-09-18'),
    isEditing: false,
  },
  {
    id: '7',
    name: 'George',
    email: 'george@example.com',
    salary: 580,
    gender: 'male',
    dob: new Date('1991-11-08'),
    position: 'Backend Developer',
    joiningDate: new Date('2018-06-11'),
    isEditing: false,
  },
  {
    id: '8',
    name: 'Hannah',
    email: 'hannah@example.com',
    salary: 720,
    gender: 'female',
    dob: new Date('1989-07-14'),
    position: 'Scrum Master',
    joiningDate: new Date('2017-02-05'),
    isEditing: false,
  },
  {
    id: '9',
    name: 'Ian',
    email: 'ian@example.com',
    salary: 610,
    gender: 'male',
    dob: new Date('1994-12-30'),
    position: 'Data Analyst',
    joiningDate: new Date('2021-03-22'),
    isEditing: false,
  },
  {
    id: '10',
    name: 'Julia',
    email: 'julia@example.com',
    salary: 730,
    gender: 'female',
    dob: new Date('1997-05-16'),
    position: 'Fullstack Developer',
    joiningDate: new Date('2022-08-08'),
    isEditing: false,
  },
  {
    id: '11',
    name: 'Kevin',
    email: 'kevin@example.com',
    salary: 640,
    gender: 'male',
    dob: new Date('1992-03-09'),
    position: 'Business Analyst',
    joiningDate: new Date('2020-01-15'),
    isEditing: false,
  },
  {
    id: '12',
    name: 'Lily',
    email: 'lily@example.com',
    salary: 700,
    gender: 'female',
    dob: new Date('1987-08-27'),
    position: 'HR Manager',
    joiningDate: new Date('2016-12-01'),
    isEditing: false,
  },
  {
    id: '13',
    name: 'Mike',
    email: 'mike@example.com',
    salary: 560,
    gender: 'male',
    dob: new Date('1993-06-03'),
    position: 'Support Engineer',
    joiningDate: new Date('2023-01-20'),
    isEditing: false,
  },
  {
    id: '14',
    name: 'Nina',
    email: 'nina@example.com',
    salary: 680,
    gender: 'female',
    dob: new Date('1990-10-18'),
    position: 'Product Owner',
    joiningDate: new Date('2018-10-10'),
    isEditing: false,
  },
  {
    id: '15',
    name: 'Oscar',
    email: 'oscar@example.com',
    salary: 600,
    gender: 'male',
    dob: new Date('1986-05-25'),
    position: 'DevOps Engineer',
    joiningDate: new Date('2015-05-15'),
    isEditing: false,
  },
];
